# .github/workflows/cron_tweet.yml

name: Chrona Bot - Weekly Tweet

on:
  schedule:
    # 毎日 23:00 UTC (日本時間 08:00) に実行
    - cron: '0 23 * * *'
  # 手動実行も可能にする (テスト用)
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Dockerイメージをビルド
      - name: Build Docker image
        run: docker build -t chrona-bot-image .

      # 3. Dockerコンテナを実行してツイート
      - name: Run Docker container and tweet
        run: |
          docker run --rm \
            -e X_API_KEY="${{ secrets.X_API_KEY }}" \
            -e X_API_SECRET="${{ secrets.X_API_SECRET }}" \
            -e X_ACCESS_TOKEN="${{ secrets.X_ACCESS_TOKEN }}" \
            -e X_ACCESS_TOKEN_SECRET="${{ secrets.X_ACCESS_TOKEN_SECRET }}" \
            -e GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}" \
            chrona-bot-image 